language: go
go:
  - 1.10.3
notifications:
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email:
    recipients:
      - ian@ianferguson.io
script:
  - go test ./...
  - golint ./...
